language: java
jdk: oraclejdk8
dist: trusty
addons:
  sonarcloud:
    organization: thiagoferrax-github
    token:
	secure: "lyoavPBsPP9tYLyFWECcPu5Ek3cSOvHT66YrDy2IJvJNauC8XrV4oYFF9oV1WDSwCI5IDUIgUD93VgyjAYbC106RHUVGJnKck+vV+DHq7HpmeBHEdN+PVnWmny9QROiWv/r/HNsu9gUM8BA7oGIaFHmCb2VwC2hzid9sZOCko11/7UckSqCSM9CNo56ZReBth3BXpsqgslO12747IAcdHBzEKWPcUL0UH4/6AF84b5hlD/QXW+lUJIheyw2Xl8ysUzTLI+PLMqrH5FU0SDhHdBwhN+5S7ZNLdPTRjik90LprD1CYnVw66z/g5TtinHI6w0z30UPF6FrU/X7FvurJL5CdE5hAkxClbEcDGQRlCPggJaffOz1WyURArxD3lM319VBQKmynaPHnHsGfFfJmYzv+DMfTObOJ8Z3aCpkfDw6ODXkfDYQQhVTeSN66EtXDlVxk1Ch03IIQb1klfohvCCtoAmp9mkkPKMpy2mJ2teVVAJf4B9hmEOa7WYTadhz4rgIqT056kZqjMuLJlhVPFL4/XkLcIKp/Quf0uB1ShcigAlG7xCG5qxjtdsALX44HNGiJnmaKnXK2mwME6t7MjACW1538QvRvJVh6pfMOLUNHFX1Az7gWzaBU97M44/470Eo4LASmpP239B78FgKAY0Ne36l68ldvMYWpDXmqu2Q="
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
