version: '3'
volumes:
   data:
networks:
   database-net:   
   backend-net:      
services:
   database:
      image: postgres:11.3
      container_name: neueda-littleurl-database
      volumes:
         - data:/var/lib/postgresql/data
         - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
         - database-net
   backend:
      container_name: neueda-littleurl-backend
      image: zenika/alpine-maven
      restart: always
      volumes:
         - .:/app
         - ~/.m2:/root/.m2
      working_dir: /app
      command: mvn clean spring-boot:run    
      ports:
         - 80:8080
      networks:
         - backend-net
         - database-net
      depends_on:
         - database